name: beinglearners
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0
  json_annotation: ^2.0.0
  flutter_launcher_icons: ^0.7.3
  splashscreen: ^1.2.0
  flutter_page_transition: ^0.1.6
  clippy_flutter: ^1.1.0
  shimmer: ^1.0.1
  intro_slider: ^2.2.5
  shared_preferences: ^0.5.4
  flutter_html: ^0.10.1
  flutter_widget_from_html_core: ^0.3.2+1
  dynamic_theme: ^1.0.0
  image_picker: ^0.6.3+4
  geocoder: ^0.2.1
  carousel_slider: ^2.3.1
  connectivity: ^0.4.4
  animated_text_kit: ^2.5.4
  date_format: ^1.0.4
  intl: ^0.16.0
  fluttertoast: ^7.1.6


dev_dependencies:
  build_runner: ^1.7.1
  json_serializable: ^2.0.0

  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/logo_transparent.png
    - images/profile_small.png
    - images/lock.png
    - images/error.png
    - images/flutter_icon.jpg
    - images/heart_icon.png
    - images/loader.gif
    - images/user.png
    - images/blog2_img.jpeg
    - images/blog3_img.jpeg
    - images/eye.png
    - images/hide_eye.png
    - images/no_data.png
    - images/logo.jpeg
    - images/blog1_img.jpeg
    - images/m1.jpg
    - images/m2.jpg
    - images/m3.jpg
    - images/m4.jpg
    - images/m5.jpg
    - images/b1.jpg
    - images/b2.jpg
    - images/b4.jpg
    - images/b5.jpg
    - images/b6.jpg
    - images/b7.jpeg
    - images/b3.jpg
    - images/loading_img.gif
    - images/data_not_found.gif
    - images/massage.jpg
    - images/offer_img.jpeg
    - images/men_service.png
    - images/women_service.png
    - images/internet_conne.png
    - images/splash.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  image_path: "icon/logo.jpeg"
  android: true
  ios: true